version: "3.7"
services:
  webapp:
    build: ./
    container_name: 'reactapp'
    ports: 
      - "3000:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/var/www/html